<a href="https://colab.research.google.com/github/shreya1110-dev/datascienceassignments/blob/main/fds1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


1. Make use of python Pandas library to get the minimum, 25th percentile, median,
75th, and max of a numeric series?
Compute the minimum, 25th percentile, median, 75th, and maximum of ser.



In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# input series
ser = pd.Series(np.random.normal(10, 5, 25))

In [ ]:
# 25th percentile
print("25th percentile: ",ser.quantile(.25))
# median
print("Median: ", ser.median())
# 75th percentile
print("75th percentile: ",ser.quantile(.75))
# max of ser
print("Maximum value: ", max(ser))

25th percentile:  7.023911995515109
Median:  10.695669973582323
75th percentile:  11.866767471047318
Maximum value:  17.45223474565785


2. Make use of python Pandas library to get frequency counts of unique items of a series? 

In [ ]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [ ]:
# frequency of unique values
ser.value_counts()

3    10
8     7
9     5
2     4
7     3
5     2
4     2
6     1
1     1
dtype: int64

3. Make use of Python Numpy library to convert a numpy array to a dataframe of given shape?
Reshape the series ser into a dataframe with 7 rows and 5 columns

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 35))
ser.values

array([5, 2, 9, 3, 8, 7, 8, 9, 3, 8, 7, 9, 3, 8, 2, 4, 3, 4, 2, 9, 6, 3,
       9, 7, 8, 8, 3, 3, 1, 3, 2, 3, 5, 8, 3])

In [ ]:
arr = ser.values

In [ ]:
arr.reshape((7,5))

array([[5, 2, 9, 3, 8],
       [7, 8, 9, 3, 8],
       [7, 9, 3, 8, 2],
       [4, 3, 4, 2, 9],
       [6, 3, 9, 7, 8],
       [8, 3, 3, 1, 3],
       [2, 3, 5, 8, 3]])

4. Build a python program to compute the mean squared error on a truth and predicted
series? Compute the mean squared error of truth and pred series.

In [ ]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [ ]:
print("Truth:", truth)
print("Prediction:", pred)

Truth: 0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
Prediction: 0    0.327497
1    1.422329
2    2.789605
3    3.273622
4    4.414406
5    5.925983
6    6.775897
7    7.849133
8    8.394019
9    9.302622
dtype: float64


In [ ]:
# variable to store the summation of differences
summation = 0  
# finding total number of items in list
n = len(truth) 
# looping through each element of the list
for i in range (0,n):  
  # finding the difference between observed and predicted value
  difference = truth[i] - pred[i]  
  # square of the difference 
  squared_difference = difference**2  
  # sum of all the differences
  summation = summation + squared_difference  
# dividing summation by total values to obtain average
MSE = summation/n  
print("The Mean Square Error is: " , MSE)

The Mean Square Error is:  0.3583013934974719


5. Build a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [ ]:
x =  np.arange(2, 11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

6. Build a NumPy program to find the real and imaginary parts of an array of complex numbers. 

In [ ]:
arr = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
real = []
imaginary = []
for num in arr:
  real.append(num.real)
  imaginary.append(num.imag)
print("Real:", real)
print("Imaginary:", imaginary)

Real: [1.0, 0.70710678]
Imaginary: [0.0, 0.70710678]


Build a NumPy program to normalize a 3x3 random matrix. 

In [ ]:
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.87615285 0.73302225 0.805261  ]
 [0.28193365 0.26046587 0.68748735]
 [0.76258111 0.97979534 0.15980793]]
After normalization:
[[0.87360478 0.69905259 0.78714998]
 [0.14893609 0.12275547 0.64352136]
 [0.73510053 1.         0.        ]]


8. Build a NumPy program to create a random vector of size 10 and sort it.

In [ ]:
arr = np.random.rand(10)
print("Random Array:",arr)
arr.sort()
print("Sorted Array:",arr)

Random Array: [0.01950065 0.5125741  0.64319711 0.24274556 0.79145738 0.79067625
 0.04927324 0.80998364 0.48460315 0.32706258]
Sorted Array: [0.01950065 0.04927324 0.24274556 0.32706258 0.48460315 0.5125741
 0.64319711 0.79067625 0.79145738 0.80998364]


9. Build a NumPy program to check two random arrays are equal or not.

In [ ]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Equality:",np.allclose(x, y))

First array:
[1 1 0 1 1 1]
Second array:
[0 1 0 0 0 1]
Equality: False


10. Build a NumPy program to find the most frequent value in an array. 




In [ ]:
from scipy import stats as st
arr = np.array([6, 9, 5, 1, 7, 5, 1, 0, 1, 5, 5, 0, 8, 9, 0, 7, 0, 7, 6, 5, 1, 1, 9, 5, 3, 8, 7, 9, 6, 3, 4, 5, 9, 7, 2, 7, 0, 2, 2, 6])
st.mode(arr)

ModeResult(mode=array([5]), count=array([7]))